id: P449D4971
initial_creation_type: input
source_metadata:
  title: Pema Karpo Series
  language: en
  description: 'Texts by the Omniscient Pema Karpo (kun mkhyen padma dkar po) aka
    Ngawang Norbu (ngag dbang nor bu, 1527-1592), a great scholar and adept of the
    Drukpa Kagyü school:'
  volume:
    66e11c1c3f75412ab405575ad5b34c75:
      title: 'A Casket of Sacred Dharma: Stages of Meditation on Dependent Arising'
      parent: Commentaries
created_at: '2022-03-01T01:15:40.964053'
last_modified_at: '2022-03-01T01:15:40.964060'
